name: Linux Workflow
on:
  push:
    paths:
      - "linux/**"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Runs a single command using the runners shell
      - name: Check if linux build is clean
        run: |
          ./install-deps.sh
          commit_num=$(git rev-parse @:./linux)
          wget https://github.com/michaelp3/linux/archive/$commit_num.zip
          unzip $commit_num.zip
          ./build-linux.sh linux-$commit_num tinyconfig
