name: Linux Workflow
on:
  push:
    paths:
      - 'linux'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Check if linux build is clean
        run: |
          ./install-deps.sh
          commit_hash=$(git rev-parse @:./linux)
          wget https://github.com/michaelp3/linux/archive/$commit_hash.zip
          unzip $commit_hash.zip
          ./build-linux.sh linux-$commit_hash tinyconfig
